spring.application.name=osu-parking
spring.datasource.url=jdbc:sqlite:C:/Users/aiden/Documents/idk/python/projects/stock_plot/osu-parking/parking.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
app.cors.allowed-origins=http://localhost:5173