spring.application.name=osu-parking

spring.datasource.url=jdbc:sqlite:/data/parking.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

app.cors.allowed-origins=http://localhost:5173,https://osu-parking.up.railway.app